// Auto-generated by pivota init-dev-server. Extends user's vite.config.ts at runtime
// to set server.allowedHosts = true (sandbox preview embedding).
// Remove this file if you set allowedHosts yourself in vite.config.ts.
import { defineConfig, mergeConfig } from 'vite';
import userConfig from './vite.config';
export default defineConfig((env) => mergeConfig(
  typeof userConfig === 'function' ? userConfig(env) : userConfig,
  { server: { allowedHosts: true } }
));
