#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent-synthesized
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Lockfile-sentinel skip combined with INSTALL_PRESENCE_CHECK — RESEARCH.md
#     Pitfall 6 (sentinel survives reboots but install output dirs may not on
#     fresh tmpfs; never skip on a clean directory).
#   - Agent-synthesized: zero catalog match (multi-process stack: Express API +
#     Vite React client + Postgres + Redis via docker compose DB services).
#   - DB services started via `docker compose up -d db redis` so postgres and
#     redis are available for the native tsx watch backend dev run.
#   - Client dev server (Vite) uses trap+wait-n pattern per RESEARCH.md Pattern 3.
#   - Migrate runs AFTER npm ci (node_modules present), BEFORE starting the server.
#   - vite.config.ts already sets host: '0.0.0.0' — no CLI override needed.

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
# `wait -n` (multi-process supervision) requires bash >= 4.3.
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === Single-instance guard ===
exec 200>/tmp/pivota-dev.lock
if ! flock -n 200; then
  echo "[pivota] start-dev.sh already running (lock held) — exiting; poll the ready port instead" >&2
  exit 0
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent-synthesized)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
# Express: listen on 0.0.0.0 (hardcoded in src/server.ts: app.listen(port, '0.0.0.0'))
export PORT="${PORT:-3000}"
export HOST=0.0.0.0
# Vite: vite.config.ts already sets server.host: '0.0.0.0' and port: 5173 — no extra env needed.
# DO NOT set NODE_ENV=production: strips devDependencies (tsx, typescript) needed for tsx watch.

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] seeding .env from .env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
      continue
    fi
    if [[ "$line" != *\"* && "$line" != *\'* ]]; then
      line="$(printf '%s' "$line" | sed -E 's/[[:space:]]+#.*$//')"
    fi
    value="${line#*=}"
    value_lc="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    if [[ "$value_lc" == change_me* || "$value_lc" == changeme* ]]; then
      generated="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
      printf '%s=%s\n' "$key" "${generated:0:48}"
      echo "[pivota] generated random value for placeholder $key" >&2
    else
      printf '%s\n' "$line"
    fi
  done < .env.example > .env
fi

# === Pre-exec: start only DB services via docker compose ===
# The compose file defines postgres + redis with proper healthchecks.
# We start ONLY the db and redis services (not the app service, which uses the
# compiled image). The backend runs natively as 'tsx watch' for live reload.
echo "[pivota] starting postgres and redis via docker compose"
docker compose up -d db redis

# Wait for DB services to be healthy before proceeding
echo "[pivota] waiting for db and redis to be healthy..."
WAIT_TRIES=30
for i in $(seq 1 $WAIT_TRIES); do
  DB_HEALTH=$(docker compose ps --format json db 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('Health','') if isinstance(d,dict) else [x.get('Health','') for x in d][0])" 2>/dev/null || echo "unknown")
  REDIS_HEALTH=$(docker compose ps --format json redis 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('Health','') if isinstance(d,dict) else [x.get('Health','') for x in d][0])" 2>/dev/null || echo "unknown")
  if [[ "$DB_HEALTH" == "healthy" && "$REDIS_HEALTH" == "healthy" ]]; then
    echo "[pivota] db and redis are healthy"
    break
  fi
  if (( i == WAIT_TRIES )); then
    echo "[pivota] WARNING: db/redis health timeout after ${WAIT_TRIES}x5s; proceeding anyway (db=${DB_HEALTH} redis=${REDIS_HEALTH})"
    break
  fi
  echo "[pivota] waiting for db/redis health (attempt $i/${WAIT_TRIES}; db=${DB_HEALTH} redis=${REDIS_HEALTH})..."
  sleep 5
done

# === D-12: idempotent install via lockfile hash + presence check ===
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH="package-lock.json"
INSTALL_PRESENCE_CHECK="node_modules"
INSTALL_CMD='npm ci --include=dev --prefer-offline 2>/dev/null || npm install --include=dev'

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  local rc=0
  bash -c "$INSTALL_CMD" || rc=$?
  if (( rc == 0 )); then
    return 0
  fi
  if [[ "$INSTALL_CMD" == *"npm "* ]]; then
    echo "[pivota] WARN install failed (exit=$rc) — retrying with --legacy-peer-deps (peer conflict force-resolved; runtime incompatibility possible)"
    local rc2=0
    npm install --legacy-peer-deps || rc2=$?
    if (( rc2 == 0 )); then
      echo "[pivota] WARN install succeeded via --legacy-peer-deps fallback — a dependency's peer range is unsatisfied; fix package.json (this is a real bug, not just a warning)"
      return 0
    fi
    rc=$rc2
  fi
  echo "[pivota] FATAL install failed (exit=$rc) — dev server cannot start; resolve the dependency conflict in the manifest" >&2
  return "$rc"
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")
  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi
  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping install"
  else
    if [[ "$PRESENCE_OK" == "0" ]]; then
      echo "[pivota] install output ($INSTALL_PRESENCE_CHECK) missing; install required"
    else
      echo "[pivota] lockfile changed (or first boot); install required"
    fi
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# Install client dependencies
CLIENT_SENTINEL="/tmp/pivota-client-setup-sentinel"
if [[ -f "client/package-lock.json" ]]; then
  CLIENT_HASH=$(sha256sum "client/package-lock.json" | cut -d' ' -f1)
  CLIENT_PREV=$(cat "$CLIENT_SENTINEL" 2>/dev/null || echo "")
  CLIENT_PRESENCE_OK=1
  if [[ ! -d "client/node_modules" ]]; then
    CLIENT_PRESENCE_OK=0
  fi
  if [[ "$CLIENT_HASH" == "$CLIENT_PREV" && "$CLIENT_PRESENCE_OK" == "1" ]]; then
    echo "[pivota] client lockfile unchanged AND node_modules present; skipping client install"
  else
    echo "[pivota] installing client dependencies"
    (cd client && npm ci --include=dev --prefer-offline 2>/dev/null || npm install --include=dev)
    echo "$CLIENT_HASH" > "$CLIENT_SENTINEL"
  fi
elif [[ ! -d "client/node_modules" ]]; then
  echo "[pivota] installing client dependencies (no lockfile sentinel)"
  (cd client && npm install --include=dev)
fi

# === Run migrations (after install, before server start) ===
# DATABASE_URL is set in the compose db service; read it from env or use default.
export DATABASE_URL="${DATABASE_URL:-postgres://grants_user:grants_pass@localhost:5432/grants_intake}"
echo "[pivota] running migrations"
npm run migrate || echo "[pivota] migrate returned non-zero (continuing — may be already migrated)"

# Run seed (idempotent — uses ON CONFLICT DO NOTHING)
echo "[pivota] running seed"
npm run seed || echo "[pivota] seed returned non-zero (continuing)"

# === Multi-process supervision: Express API + Vite client dev server ===
# Pattern: bash trap + background PIDs + wait -n (RESEARCH.md Pattern 3).
# Do NOT use concurrently / pm2 / supervisord.

shutdown() {
  echo "[pivota] shutting down children"
  kill -TERM "${PIDS[@]}" 2>/dev/null || true
  sleep 2
  kill -KILL "${PIDS[@]}" 2>/dev/null || true
  wait
  # Stop compose DB services on exit
  docker compose stop db redis 2>/dev/null || true
}
trap shutdown SIGTERM SIGINT EXIT

declare -a PIDS=()

# Process 1: Express API backend (tsx watch for live reload, port 3000)
(
  cd /home/daytona/project \
    && : \
    && exec bash -c 'npm run dev'
) 2>&1 | sed 's/^/[backend] /' &
PIDS+=($!)

# Brief pause to let the backend initialize before starting the client
sleep 3

# Process 2: Vite client dev server (port 5173, proxies /api to localhost:3000)
# vite.config.ts already sets host: '0.0.0.0' and port: 5173 with proxy to :3000
(
  cd /home/daytona/project/client \
    && : \
    && exec bash -c 'npm run dev'
) 2>&1 | sed 's/^/[client] /' &
PIDS+=($!)

echo "[pivota] backend (port 3000) and client (port 5173) started; waiting for any to exit"

# Wait for ANY child to exit; if one dies, the trap tears down siblings.
wait -n
EXIT_CODE=$?
echo "[pivota] a child process exited (code=$EXIT_CODE); shutting down"
shutdown
exit "$EXIT_CODE"

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations (plan 06's regen logic detects
# the marker and re-appends user content verbatim after re-emitting the preamble).
